const leagues = {
    nba: {
        name: "NBA",
        teams: [
            { id: "hawks", name: "Atlanta Hawks" },
            { id: "celtics", name: "Boston Celtics" },
            { id: "nets", name: "Brooklyn Nets" },
            { id: "hornets", name: "Charlotte Hornets" },
            { id: "bulls", name: "Chicago Bulls" },
            { id: "cavaliers", name: "Cleveland Cavaliers" },
            { id: "mavericks", name: "Dallas Mavericks" },
            { id: "nuggets", name: "Denver Nuggets" },
            { id: "pistons", name: "Detroit Pistons" },
            { id: "warriors", name: "Golden State Warriors" },
            { id: "rockets", name: "Houston Rockets" },
            { id: "pacers", name: "Indiana Pacers" },
            { id: "clippers", name: "LA Clippers" },
            { id: "lakers", name: "Los Angeles Lakers" },
            { id: "grizzlies", name: "Memphis Grizzlies" },
            { id: "heat", name: "Miami Heat" },
            { id: "bucks", name: "Milwaukee Bucks" },
            { id: "timberwolves", name: "Minnesota Timberwolves" },
            { id: "pelicans", name: "New Orleans Pelicans" },
            { id: "knicks", name: "New York Knicks" },
            { id: "thunder", name: "Oklahoma City Thunder" },
            { id: "magic", name: "Orlando Magic" },
            { id: "76ers", name: "Philadelphia 76ers" },
            { id: "suns", name: "Phoenix Suns" },
            { id: "trailblazers", name: "Portland Trail Blazers" },
            { id: "kings", name: "Sacramento Kings" },
            { id: "spurs", name: "San Antonio Spurs" },
            { id: "raptors", name: "Toronto Raptors" },
            { id: "jazz", name: "Utah Jazz" },
            { id: "wizards", name: "Washington Wizards" }
        ]
    },
    nfl: {
        name: "NFL",
        teams: [
            { id: "cardinals", name: "Arizona Cardinals" },
            { id: "falcons", name: "Atlanta Falcons" },
            { id: "ravens", name: "Baltimore Ravens" },
            { id: "bills", name: "Buffalo Bills" },
            { id: "panthers", name: "Carolina Panthers" },
            { id: "bears", name: "Chicago Bears" },
            { id: "bengals", name: "Cincinnati Bengals" },
            { id: "browns", name: "Cleveland Browns" },
            { id: "cowboys", name: "Dallas Cowboys" },
            { id: "broncos", name: "Denver Broncos" },
            { id: "lions", name: "Detroit Lions" },
            { id: "packers", name: "Green Bay Packers" },
            { id: "texans", name: "Houston Texans" },
            { id: "colts", name: "Indianapolis Colts" },
            { id: "jaguars", name: "Jacksonville Jaguars" },
            { id: "chiefs", name: "Kansas City Chiefs" },
            { id: "raiders", name: "Las Vegas Raiders" },
            { id: "chargers", name: "Los Angeles Chargers" },
            { id: "rams", name: "Los Angeles Rams" },
            { id: "dolphins", name: "Miami Dolphins" },
            { id: "vikings", name: "Minnesota Vikings" },
            { id: "patriots", name: "New England Patriots" },
            { id: "saints", name: "New Orleans Saints" },
            { id: "giants", name: "New York Giants" },
            { id: "jets", name: "New York Jets" },
            { id: "eagles", name: "Philadelphia Eagles" },
            { id: "steelers", name: "Pittsburgh Steelers" },
            { id: "49ers", name: "San Francisco 49ers" },
            { id: "seahawks", name: "Seattle Seahawks" },
            { id: "buccaneers", name: "Tampa Bay Buccaneers" },
            { id: "titans", name: "Tennessee Titans" },
            { id: "commanders", name: "Washington Commanders" }
        ]
    },
    nhl: {
        name: "NHL",
        teams: [
            { id: "ducks", name: "Anaheim Ducks" },
            { id: "coyotes", name: "Arizona Coyotes" },
            { id: "bruins", name: "Boston Bruins" },
            { id: "sabres", name: "Buffalo Sabres" },
            { id: "flames", name: "Calgary Flames" },
            { id: "hurricanes", name: "Carolina Hurricanes" },
            { id: "blackhawks", name: "Chicago Blackhawks" },
            { id: "avalanche", name: "Colorado Avalanche" },
            { id: "bluejackets", name: "Columbus Blue Jackets" },
            { id: "stars", name: "Dallas Stars" },
            { id: "redwings", name: "Detroit Red Wings" },
            { id: "oilers", name: "Edmonton Oilers" },
            { id: "panthers", name: "Florida Panthers" },
            { id: "kings", name: "Los Angeles Kings" },
            { id: "wild", name: "Minnesota Wild" },
            { id: "canadiens", name: "Montreal Canadiens" },
            { id: "predators", name: "Nashville Predators" },
            { id: "devils", name: "New Jersey Devils" },
            { id: "islanders", name: "New York Islanders" },
            { id: "rangers", name: "New York Rangers" },
            { id: "senators", name: "Ottawa Senators" },
            { id: "flyers", name: "Philadelphia Flyers" },
            { id: "penguins", name: "Pittsburgh Penguins" },
            { id: "sharks", name: "San Jose Sharks" },
            { id: "kraken", name: "Seattle Kraken" },
            { id: "blues", name: "St. Louis Blues" },
            { id: "lightning", name: "Tampa Bay Lightning" },
            { id: "mapleleafs", name: "Toronto Maple Leafs" },
            { id: "canucks", name: "Vancouver Canucks" },
            { id: "goldenknights", name: "Vegas Golden Knights" },
            { id: "capitals", name: "Washington Capitals" },
            { id: "jets", name: "Winnipeg Jets" }
        ]
    },
    mlb: {
        name: "MLB",
        teams: [
            { id: "diamondbacks", name: "Arizona Diamondbacks" },
            { id: "braves", name: "Atlanta Braves" },
            { id: "orioles", name: "Baltimore Orioles" },
            { id: "redsox", name: "Boston Red Sox" },
            { id: "whitesox", name: "Chicago White Sox" },
            { id: "cubs", name: "Chicago Cubs" },
            { id: "reds", name: "Cincinnati Reds" },
            { id: "guardians", name: "Cleveland Guardians" },
            { id: "rockies", name: "Colorado Rockies" },
            { id: "tigers", name: "Detroit Tigers" },
            { id: "astros", name: "Houston Astros" },
            { id: "royals", name: "Kansas City Royals" },
            { id: "angels", name: "Los Angeles Angels" },
            { id: "dodgers", name: "Los Angeles Dodgers" },
            { id: "marlins", name: "Miami Marlins" },
            { id: "brewers", name: "Milwaukee Brewers" },
            { id: "twins", name: "Minnesota Twins" },
            { id: "mets", name: "New York Mets" },
            { id: "yankees", name: "New York Yankees" },
            { id: "athletics", name: "Oakland Athletics" },
            { id: "phillies", name: "Philadelphia Phillies" },
            { id: "pirates", name: "Pittsburgh Pirates" },
            { id: "padres", name: "San Diego Padres" },
            { id: "giants", name: "San Francisco Giants" },
            { id: "mariners", name: "Seattle Mariners" },
            { id: "cardinals", name: "St. Louis Cardinals" },
            { id: "rays", name: "Tampa Bay Rays" },
            { id: "rangers", name: "Texas Rangers" },
            { id: "bluejays", name: "Toronto Blue Jays" },
            { id: "nationals", name: "Washington Nationals" }
        ]
    },
    laliga: {
        name: "La Liga",
        teams: [
            { id: "barcelona", name: "FC Barcelona" },
            { id: "realmadrid", name: "Real Madrid" },
            { id: "atleticomadrid", name: "Atletico Madrid" },
            { id: "sevilla", name: "Sevilla FC" },
            { id: "valencia", name: "Valencia CF" },
            { id: "villarreal", name: "Villarreal CF" },
            { id: "betis", name: "Real Betis" },
            { id: "athletic", name: "Athletic Club" },
            { id: "osasuna", name: "CA Osasuna" },
            { id: "espanyol", name: "RCD Espanyol" },
            { id: "celta", name: "Celta Vigo" },
            { id: "mallorca", name: "RCD Mallorca" },
            { id: "almeria", name: "UD Almeria" },
            { id: "getafe", name: "Getafe CF" },
            { id: "rayo", name: "Rayo Vallecano" },
            { id: "valladolid", name: "Real Valladolid" },
            { id: "elche", name: "Elche CF" },
            { id: "cadiz", name: "Cadiz CF" },
            { id: "levante", name: "Levante UD" },
            { id: "granada", name: "Granada CF" }
        ]
    },
    premierleague: {
        name: "Premier League",
        teams: [
            { id: "arsenal", name: "Arsenal" },
            { id: "astonvilla", name: "Aston Villa" },
            { id: "bournemouth", name: "AFC Bournemouth" },
            { id: "brentford", name: "Brentford" },
            { id: "brighton", name: "Brighton & Hove Albion" },
            { id: "burnley", name: "Burnley" },
            { id: "chelsea", name: "Chelsea" },
            { id: "crystalpalace", name: "Crystal Palace" },
            { id: "everton", name: "Everton" },
            { id: "fulham", name: "Fulham" },
            { id: "liverpool", name: "Liverpool" },
            { id: "manchestercity", name: "Manchester City" },
            { id: "manchesterunited", name: "Manchester United" },
            { id: "newcastle", name: "Newcastle United" },
            { id: "nottinghamforest", name: "Nottingham Forest" },
            { id: "sheffieldunited", name: "Sheffield United" },
            { id: "tottenham", name: "Tottenham Hotspur" },
            { id: "westham", name: "West Ham United" },
            { id: "wolves", name: "Wolverhampton Wanderers" }
        ]
    },
    bundesliga: {
        name: "Bundesliga",
        teams: [
            { id: "bayern", name: "Bayern Munich" },
            { id: "dortmund", name: "Borussia Dortmund" },
            { id: "leipzig", name: "RB Leipzig" },
            { id: "leverkusen", name: "Bayer Leverkusen" },
            { id: "frankfurt", name: "Eintracht Frankfurt" },
            { id: "wolfsburg", name: "VfL Wolfsburg" },
            { id: "gladbach", name: "Borussia Monchengladbach" },
            { id: "freiburg", name: "SC Freiburg" },
            { id: "mainz", name: "FSV Mainz 05" },
            { id: "augsburg", name: "FC Augsburg" },
            { id: "stuttgart", name: "VfB Stuttgart" },
            { id: "bremen", name: "Werder Bremen" },
            { id: "schalke", name: "FC Schalke 04" },
            { id: "unionberlin", name: "Union Berlin" },
            { id: "bochum", name: "VfL Bochum" },
            { id: "hoffenheim", name: "TSG Hoffenheim" },
            { id: "koln", name: "1. FC Koln" },
            { id: "hertha", name: "Hertha Berlin" }
        ]
    },
    seriea: {
        name: "Serie A",
        teams: [
            { id: "juventus", name: "Juventus" },
            { id: "inter", name: "Inter Milan" },
            { id: "milan", name: "AC Milan" },
            { id: "napoli", name: "Napoli" },
            { id: "roma", name: "AS Roma" },
            { id: "lazio", name: "Lazio" },
            { id: "fiorentina", name: "Fiorentina" },
            { id: "atalanta", name: "Atalanta" },
            { id: "torino", name: "Torino" },
            { id: "bologna", name: "Bologna" },
            { id: "sassuolo", name: "Sassuolo" },
            { id: "udinese", name: "Udinese" },
            { id: "verona", name: "Hellas Verona" },
            { id: "sampdoria", name: "Sampdoria" },
            { id: "genoa", name: "Genoa" },
            { id: "lecce", name: "Lecce" },
            { id: "salernitana", name: "Salernitana" },
            { id: "cagliari", name: "Cagliari" }
        ]
    }
};

module.exports = leagues;